### ISSUE TITLE
LeagueJS and Crodova?

### ISSUE THREAD

**Issue by SertyDev** [Colorfulstan/LeagueJS#10]
Hello, I am using Cordova and after looking for two days and before asking in some Cordova forum I wanted to know if it´s possible to use LeagueJS in this kind of technology. I installed it (so it is in node_modules) but I can´t find the module in the JS using require() (cordova.require() in my case).

Thank you.

**Comment by Colorfulstan** [comment]
Hey,
im sorry, I don't have experience with cordova.

Just from a quick google search, you might need to make sure the library is included within your www folder!?

https://stackoverflow.com/questions/46466372/how-do-i-load-node-modules-in-cordova-web-browser-modules-not-node-js-specifi

Guess you have propably found that yourself already.

What does your require call / usage look like?
What error messages do you get when trying to require it?

**Comment by SertyDev** [comment]
Hello,

Thank you very much for your response.

At the end I decided to create a custom API just for the methods I need (my first API btw xD)

But this looks pretty relevant : "**you might need to make sure the library is included within your www folder**"

The error was just "module not found" but, as I said I got courage and started my first API and is running so far xD

Again thank you very much!
