### ISSUE TITLE
Deprecation of the lol-static-data-v3 API

### ISSUE THREAD

**Issue by Colorfulstan** [Colorfulstan/LeagueJS#11]
https://discussion.developer.riotgames.com/articles/5719/removal-of-the-lol-static-data-v3-api.html

August 27th Static Data endpoints will be removed.

I'm in the process of adding DataDragon support, but not sure if I will get to rewire all the methods in time.

Simply delivering the DataDragon files through the endpoint methods would be a good first step to prevent a breaking change, but adding the options back in might be a pain, and possibly not worth the effort.

Open for discussion and contribution, will update here when the DataDragon integration is live.

**Comment by Colorfulstan** [comment]
https://github.com/Colorfulstan/LeagueJS/tree/DataDragonHelper
contains a first iteration of DataDragon integration.

Found on npm as leaguejs@beta

**Comment by Colorfulstan** [comment]
Release candidate:
https://www.npmjs.com/package/leaguejs/v/1.10.0-beta.8

Testing it in my projects and when nothing else comes up will squash/rebase into master for 1.10.0

Old Code should not be effected, but returned properties from gettingChampions will differ and might break some edge cases.
Tags will have no effect anymore, unless used with gettingChampions (to either get the smaller champion.json or championFull.json file).

**Comment by Colorfulstan** [comment]
https://github.com/Colorfulstan/LeagueJS/compare/v1.9.1...v1.10.0

**Comment by WeihengLu** [comment]
New to data dragon, for getting static data like "Jax  W spell scale with XX ad ratio", so I just use URL like "http://ddragon.leagueoflegends.com/cdn/6.5.1/data/en_US/champion/Jax.json" to get the JSON and extract and look at the ad ratio in JSON manually?

**Comment by Colorfulstan** [comment]
Sorry for being late...

Doesn't look like an Issue with the Library but with the data you get.
But your general idea is correct, you get the respective json file (note the version in the url!) and get the static data from there.

You'll be able to find help on the RIOT Api developers Discord more easily then in the issues here :)
 https://discord.gg/riotapi
