### ISSUE TITLE
Match-V5 support

### ISSUE THREAD

**Issue by bangingheads** [Colorfulstan/LeagueJS#26]
Match-V4 support is being deprecated on September 13, 2021.

Match-V5 is now available for production keys.

For this library to stay relevant it will need Match-V5 support.

**Comment by Colorfulstan** [comment]
Will add that over the weekend.

Not sure how much of the previous helper methods for the endpoint can be migrated safely.
If I can do a seemless internal migration I will do so.

Otherwise I'll just add the methods for the new endpoints (sooner)
