### ISSUE TITLE
Deprecation of LeagueEndpoint.gettingLeagueBySummonerId

### ISSUE THREAD

**Issue by Colorfulstan** [Colorfulstan/LeagueJS#4]
https://discussion.developer.riotgames.com/articles/3677/the-deprecation-of-the-league-v3getallleaguesforsu.html

- [x] add Deprecation warning and note
- [x] add new getLeagueById implementation
- [ ] ~update docs regarding new leagueId property~
- [ ] ~propably add leagueIds to GameConstants~

Endpoint will be removed on January 10th

Since the breaking change is not imposed by the library and since the endpoint will stop working within the old versions anyways, versioning will propably stay on 1.x

**Comment by matthewferderber** [comment]
I'm interested in helping out for this.

I don't think leagueId is a Constant. It's similar to SummonerId or AccountId (it's a UUID).
